Refactor proposal types for streamlined action handling
ElliotFriedman/standard-repo pull request #1
Opened 2023-12-12 14:51 UTC by anajuliabit

2023-12-13 07:31 UTC, ElliotFriedman commented on proposals/proposalTypes/CrossChainProposal.sol
>      function _simulateCrossChainActions(address timelockAddress) internal {
if this function just calls another function and doesn't override anything, can we just get rid of it entirely?

2023-12-13 07:33 UTC, ElliotFriedman commented on proposals/proposalTypes/MultisigProposal.sol
> -abstract contract MultisigProposal is Proposal {
we will want a multisig proposal contract.

a multisig proposal type will need to encode bulk actions for the multisig and leverage multicall with delegatecalls to enable arbitrary calls to arbitrary contracts

2023-12-13 17:35 UTC, ElliotFriedman commented on addresses/Addresses.sol
> +        if(currentAddress != address(0)) {
if you're going to use custom errors, you'll need to remove all the require statements everywhere else. I prefer using require statements as we don't need to worry about gas efficiency because this code is never getting deployed, it will only be used on a developer's machine, and having error messages that are human readable goes a long way for the developer's experience they will have when they use this system.

2023-12-13 17:35 UTC, ElliotFriedman commented on addresses/Addresses.sol
> +
remove extra newline

2023-12-13 17:35 UTC, ElliotFriedman commented on addresses/Addresses.sol
> +            revert AddressNotFound(name);
style: prefer require to custom error

2023-12-13 17:36 UTC, ElliotFriedman commented on addresses/IAddresses.sol
> +    event ResetAddresses(uint256 chainId);
natspec

2023-12-13 17:44 UTC, ElliotFriedman commented on proposals/TestProposals.sol
> +        addresses = new Addresses(addressesPath);
it's worth looking through moonwell, ztx, and volt and seeing how many different times and in what places the addresses contract is created.

if it is created all over the place, it might be a pain to have to pass this, and maybe projects would need to create a fixture that contains the addresses object that has a hardcoded path, and then instead of needing to create a new addresses object, they just inherit this object which has a state variable that references the Addresses object.

2023-12-13 17:54 UTC, ElliotFriedman commented on proposals/TestProposals.sol
> +        addresses = new Addresses(addressesPath);
It would be good to create an example of this

2023-12-13 20:52 UTC, ElliotFriedman commented on addresses/Addresses.sol
> +        require(addr != address(0), "Address not found");
let's add both the chain id and name in the error message to make it easier to debug

2023-12-13 20:53 UTC, ElliotFriedman commented on proposals/proposalTypes/Proposal.sol
> +    function _pushAction(uint256 value, address target, bytes memory data)  internal {
let's add another version of this function with 2 params, target and data

2023-12-13 20:53 UTC, ElliotFriedman commented on proposals/proposalTypes/Proposal.sol
> +    function _pushAction(uint256 value, address target, bytes memory data)  internal {
it will call push action with 0 value and empty description

2023-12-14 11:36 UTC, anajuliabit commented on addresses/Addresses.sol
> +        require(addr != address(0), "Address not found");
how do you do that without using custom errors?
we could use `string(abi.encodePacked)..` but I don't think it would be efficient

2023-12-14 17:57 UTC, ElliotFriedman commented on addresses/Addresses.sol
> +        require(addr != address(0), "Address not found");
yes,

string(abi.encodePacked("address not found: ", name, " chainid: ", itoa(_chainId));

2023-12-14 18:39 UTC, ElliotFriedman commented
This code is not compiling when I pull down and build.

<img width="868" alt="Screenshot 2023-12-14 at 10 39 43 AM" src="https://github.com/ElliotFriedman/standard-repo/assets/34463580/ded58a5c-7888-4ba2-ac41-b8d3da1164a0">

2023-12-14 20:33 UTC, ElliotFriedman commented on proposals/proposalTypes/Proposal.sol
> +     }
remove

2023-12-14 20:33 UTC, ElliotFriedman commented on proposals/proposalTypes/Proposal.sol
> +        function deploy() public virtual;
conform to old IProposal interface which means taking params `Addresses,address`

2023-12-14 20:34 UTC, ElliotFriedman commented on proposals/proposalTypes/Proposal.sol
> +    function _posCheck() internal virtual {}
what is the right place for these?

2023-12-14 20:38 UTC, ElliotFriedman commented on proposals/proposalTypes/Proposal.sol
> +    function _posCheck() internal virtual {}
remove

2023-12-14 20:38 UTC, ElliotFriedman commented on proposals/proposalTypes/Proposal.sol
> +        // @TODO maybe we could call execute here
remove

2023-12-14 20:39 UTC, ElliotFriedman commented on proposals/proposalTypes/Proposal.sol
> +    function execute() public {
remove

2023-12-14 20:39 UTC, ElliotFriedman commented on proposals/proposalTypes/CrossChainProposal.sol
> +        super._pushAction(value, target, data, description);
can we just call _pushAction directly?

2023-12-14 20:40 UTC, ElliotFriedman commented on .gitmodules
> +[submodule "lib/safe-contracts"]
let's remove for now

2023-12-14 20:47 UTC, anajuliabit commented on proposals/proposalTypes/CrossChainProposal.sol
> +        super._pushAction(value, target, data, description);
I made this way so ew can use the same function name (_pushAction)

2023-12-14 21:13 UTC, ElliotFriedman commented on proposals/proposalTypes/MultisigProposal.sol
> +    function run(Addresses addresses) public override {
let's remove this for now, and roll back to the previous multisig proposal file, just without the storage as we can now leverage the actions stored in `Proposal.sol`.

2023-12-14 21:15 UTC, ElliotFriedman commented on proposals/proposalTypes/MultisigProposal.sol
> +    function run(Addresses addresses) public override {
for now let's remove any simulation actions in this file because that is currently covered in `Proposal.sol`'s  `_simulateActions()` function. We can add this encoding and building of calldata in a separate PR.

2023-12-14 21:16 UTC, ElliotFriedman commented on proposals/proposalTypes/Proposal.sol
> +        // @TODO maybe we could call execute here
Constructor should not execute the proposal. We should remove this comment and newline

2023-12-14 22:04 UTC, ElliotFriedman commented on addresses/Addresses.sol
> +        require(addr != address(0), "Address not set");
add a more customized error here in the require statement explaining the address that was being looked for that was not found.

string(abi.encodePacked("Address not set: ", name, " chainid: ", itoa(_chainId)))

2023-12-14 22:06 UTC, ElliotFriedman commented on addresses/Addresses.sol
> +        require(currentAddress == address(0), "Address already set");
add custom error here that lets the developer know what the name being referenced was that was not set, and which chain id was being queried. this will save developer time when they need to debug issues in the future as they will know which address will not be set.

2023-12-14 22:06 UTC, ElliotFriedman commented on addresses/Addresses.sol
> +
remove extra newline

2023-12-14 22:07 UTC, ElliotFriedman commented on proposals/proposalTypes/Proposal.sol
> +
remove extra newline

2023-12-15 01:29 UTC, ElliotFriedman commented on addresses/Addresses.sol
> +        require(addr != address(0), string(abi.encodePacked("Address for proposal ", name, "not set on chain ", _chainId)));
you can't just do the raw chainid as that won't be readable. You'll need to pull in an integer to ascii function to print out the number in non hex format for the developer reading the error

2023-12-15 01:29 UTC, ElliotFriedman commented on addresses/Addresses.sol
> +        require(currentAddress == address(0), string(abi.encodePacked("Address for proposal ", name, "already set on chain ", _chainId)));
you can't just do the raw chainid as that won't be readable. You'll need to pull in an integer to ascii function to print out the number in non hex format for the developer reading the error

2023-12-15 06:31 UTC, ElliotFriedman commented on addresses/Addresses.sol
> +        require(addr != address(0), "Address not set");
just pull in this function from OZ but don't pull in the entire oz library as we only need this function https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/Strings.sol#L24-L44

2023-12-15 18:05 UTC, ElliotFriedman requested changes

2023-12-15 18:05 UTC, ElliotFriedman commented on proposals/proposalTypes/MultisigProposal.sol
> +pragma solidity 0.8.20;
Projects on L2's can't use solidity 0.8.20, so if we are locked to a higher solidity version, it might not work. If you want to change the version, we're better off locking things to a range like openzeppelin to work well with whatever version of solidity projects have.

2023-12-15 18:06 UTC, ElliotFriedman commented on proposals/proposalTypes/MultisigProposal.sol
> +pragma solidity 0.8.20;
https://eips.ethereum.org/EIPS/eip-3855

2023-12-15 18:06 UTC, ElliotFriedman commented on foundry.toml
> +solc = "0.8.20"
revert

2023-12-15 18:10 UTC, ElliotFriedman commented on addresses/Addresses.sol
> +import {Strings} from "@openzeppelin/utils/Strings.sol";
I specifically asked for the entire oz library to not be imported. Let's remove that import and only import the .toString() method by importing only the Strings.sol file into a new folder called `utils/`.

2023-12-15 18:50 UTC, ElliotFriedman approved these changes

2023-12-15 18:51 UTC, ElliotFriedman commented
It's not compiling. We can't merge it until compiles

2023-12-15 18:57 UTC, ElliotFriedman commented on addresses/Addresses.sol
> +        require(currentAddress == address(0), string(abi.encodePacked("Address for proposal ", name, "already set on chain ", _chainId.toString())));
```suggestion
        require(currentAddress == address(0), string(abi.encodePacked("Address: ", name, " already set on chain: ", _chainId.toString())));
```

2023-12-15 18:58 UTC, ElliotFriedman commented on addresses/Addresses.sol
> +        require(addr != address(0), string(abi.encodePacked("Address for proposal ", name, "not set on chain ", _chainId.toString())));
```suggestion
        require(addr != address(0), string(abi.encodePacked("Address: ", name, " not set on chain: ", _chainId.toString())));
```

2023-12-15 19:00 UTC, ElliotFriedman commented on addresses/Addresses.sol
> +    constructor(string memory addressesPath) {
There should be unit tests for this file.

2023-12-15 19:31 UTC, ElliotFriedman commented on proposals/proposalTypes/MultisigProposal.sol
> +contract MultisigProposal is Proposal {
I've figured out how to structure this.

Let's leave in the `_simulateMultisigActions` function, and override the run function in Multisig Proposal, and revert, with a message saying you must override the run function, and in it call `_simulateMultisigActions` with the address of your multisig to simulate actions.

2023-12-15 19:33 UTC, anajuliabit commented on proposals/proposalTypes/MultisigProposal.sol
> +contract MultisigProposal is Proposal {
I'm working on a new pull request specifically for the MultiSigProposal since this is getting big. I'll address it there.

2023-12-15 19:36 UTC, anajuliabit commented on addresses/Addresses.sol
> +    constructor(string memory addressesPath) {
check slack

2023-12-15 20:01 UTC, merged